// lib/country-codes.ts
export const countryCodes = [
    { code: "+1", name: "USA / Canada" },
    { code: "+44", name: "UK" },
    { code: "+91", name: "India" },
    { code: "+61", name: "Australia" },
    { code: "+49", name: "Germany" },
    { code: "+33", name: "France" },
    { code: "+81", name: "Japan" },
    { code: "+86", name: "China" },
    { code: "+55", name: "Brazil" },
    { code: "+27", name: "South Africa" },
    { code: "+971", name: "UAE" },
    { code: "+62", name: "Indonesia" },
    { code: "+60", name: "Malaysia" },
    { code: "+65", name: "Singapore" },
    { code: "+82", name: "South Korea" },
    { code: "+34", name: "Spain" },
    { code: "+39", name: "Italy" },
    { code: "+7", name: "Russia" },
    { code: "+52", name: "Mexico" },
    { code: "+234", name: "Nigeria" },
    { code: "+20", name: "Egypt" },
    { code: "+92", name: "Pakistan" },
    { code: "+880", name: "Bangladesh" },
    { code: "+94", name: "Sri Lanka" },
    { code: "+977", name: "Nepal" },
    { code: "+974", name: "Qatar" },
    { code: "+966", name: "Saudi Arabia" },
    { code: "+972", name: "Israel" },
    { code: "+90", name: "Turkey" },
    { code: "+353", name: "Ireland" },
    { code: "+46", name: "Sweden" },
    { code: "+47", name: "Norway" },
    { code: "+45", name: "Denmark" },
    { code: "+358", name: "Finland" },
    { code: "+41", name: "Switzerland" },
    { code: "+43", name: "Austria" },
    { code: "+32", name: "Belgium" },
    { code: "+31", name: "Netherlands" },
    { code: "+351", name: "Portugal" },
    { code: "+30", name: "Greece" },
    { code: "+36", name: "Hungary" },
    { code: "+48", name: "Poland" },
    { code: "+420", name: "Czech Republic" },
    { code: "+40", name: "Romania" },
    { code: "+380", name: "Ukraine" },
    { code: "+254", name: "Kenya" },
    { code: "+233", name: "Ghana" },
    { code: "+251", name: "Ethiopia" },
    { code: "+243", name: "DR Congo" },
    { code: "+250", name: "Rwanda" },
    { code: "+255", name: "Tanzania" },
    { code: "+260", name: "Zambia" },
    { code: "+263", name: "Zimbabwe" },
    { code: "+265", name: "Malawi" },
    { code: "+268", name: "Eswatini" },
    { code: "+266", name: "Lesotho" },
    { code: "+267", name: "Botswana" },
    { code: "+264", name: "Namibia" },
    { code: "+258", name: "Mozambique" },
    { code: "+269", name: "Comoros" },
    { code: "+262", name: "Reunion" },
    { code: "+261", name: "Madagascar" },
    { code: "+248", name: "Seychelles" },
    { code: "+230", name: "Mauritius" },
    { code: "+249", name: "Sudan" },
    { code: "+218", name: "Libya" },
    { code: "+216", name: "Tunisia" },
    { code: "+212", name: "Morocco" },
    { code: "+213", name: "Algeria" },
    { code: "+220", name: "Gambia" },
    { code: "+221", name: "Senegal" },
    { code: "+222", name: "Mauritania" },
    { code: "+223", name: "Mali" },
    { code: "+224", name: "Guinea" },
    { code: "+225", name: "Ivory Coast" },
    { code: "+226", name: "Burkina Faso" },
    { code: "+227", name: "Niger" },
    { code: "+228", name: "Togo" },
    { code: "+229", name: "Benin" },
    { code: "+231", name: "Liberia" },
    { code: "+232", name: "Sierra Leone" },
    { code: "+235", name: "Chad" },
    { code: "+236", name: "Central African Republic" },
    { code: "+237", name: "Cameroon" },
    { code: "+240", name: "Equatorial Guinea" },
    { code: "+241", name: "Gabon" },
    { code: "+242", name: "Congo" },
    { code: "+244", name: "Angola" },
    { code: "+245", name: "Guinea-Bissau" },
    { code: "+246", name: "Diego Garcia" },
    { code: "+247", name: "Ascension Island" },
    { code: "+248", name: "Seychelles" },
    { code: "+249", name: "Sudan" },
    { code: "+252", name: "Somalia" },
    { code: "+253", name: "Djibouti" },
    { code: "+256", name: "Uganda" },
    { code: "+257", name: "Burundi" },
    { code: "+260", name: "Zambia" },
    { code: "+261", name: "Madagascar" },
    { code: "+262", name: "Reunion" },
    { code: "+263", name: "Zimbabwe" },
    { code: "+264", name: "Namibia" },
    { code: "+265", name: "Malawi" },
    { code: "+266", name: "Lesotho" },
    { code: "+267", name: "Botswana" },
    { code: "+268", name: "Eswatini" },
    { code: "+269", name: "Comoros" },
    { code: "+290", name: "Saint Helena" },
    { code: "+291", name: "Eritrea" },
    { code: "+297", name: "Aruba" },
    { code: "+298", name: "Faroe Islands" },
    { code: "+299", name: "Greenland" },
    { code: "+350", name: "Gibraltar" },
    { code: "+351", name: "Portugal" },
    { code: "+352", name: "Luxembourg" },
    { code: "+354", name: "Iceland" },
    { code: "+355", name: "Albania" },
    { code: "+356", name: "Malta" },
    { code: "+357", name: "Cyprus" },
    { code: "+359", name: "Bulgaria" },
    { code: "+370", name: "Lithuania" },
    { code: "+371", name: "Latvia" },
    { code: "+372", name: "Estonia" },
    { code: "+373", name: "Moldova" },
    { code: "+374", name: "Armenia" },
    { code: "+375", name: "Belarus" },
    { code: "+376", name: "Andorra" },
    { code: "+377", name: "Monaco" },
    { code: "+378", name: "San Marino" },
    { code: "+379", name: "Vatican City" },
    { code: "+380", name: "Ukraine" },
    { code: "+381", name: "Serbia" },
    { code: "+382", name: "Montenegro" },
    { code: "+383", name: "Kosovo" },
    { code: "+385", name: "Croatia" },
    { code: "+386", name: "Slovenia" },
    { code: "+387", name: "Bosnia and Herzegovina" },
    { code: "+389", name: "North Macedonia" },
    { code: "+421", name: "Slovakia" },
    { code: "+423", name: "Liechtenstein" },
    { code: "+500", name: "Falkland Islands" },
    { code: "+501", name: "Belize" },
    { code: "+502", name: "Guatemala" },
    { code: "+503", name: "El Salvador" },
    { code: "+504", name: "Honduras" },
    { code: "+505", name: "Nicaragua" },
    { code: "+506", name: "Costa Rica" },
    { code: "+507", name: "Panama" },
    { code: "+508", name: "Saint Pierre and Miquelon" },
    { code: "+509", name: "Haiti" },
    { code: "+590", name: "Guadeloupe" },
    { code: "+591", name: "Bolivia" },
    { code: "+592", name: "Guyana" },
    { code: "+593", name: "Ecuador" },
    { code: "+594", name: "French Guiana" },
    { code: "+595", name: "Paraguay" },
    { code: "+596", name: "Martinique" },
    { code: "+597", name: "Suriname" },
    { code: "+598", name: "Uruguay" },
    { code: "+599", name: "Caribbean Netherlands" },
    { code: "+670", name: "Timor-Leste" },
    { code: "+672", name: "Norfolk Island" },
    { code: "+673", name: "Brunei" },
    { code: "+674", name: "Nauru" },
    { code: "+675", name: "Papua New Guinea" },
    { code: "+676", name: "Tonga" },
    { code: "+677", name: "Solomon Islands" },
    { code: "+678", name: "Vanuatu" },
    { code: "+679", name: "Fiji" },
    { code: "+680", name: "Palau" },
    { code: "+681", name: "Wallis and Futuna" },
    { code: "+682", name: "Cook Islands" },
    { code: "+683", name: "Niue" },
    { code: "+685", name: "Samoa" },
    { code: "+686", name: "Kiribati" },
    { code: "+687", name: "New Caledonia" },
    { code: "+688", name: "Tuvalu" },
    { code: "+689", name: "French Polynesia" },
    { code: "+690", name: "Tokelau" },
    { code: "+691", name: "Micronesia" },
    { code: "+692", name: "Marshall Islands" },
    { code: "+850", name: "North Korea" },
    { code: "+852", name: "Hong Kong" },
    { code: "+853", name: "Macau" },
    { code: "+855", name: "Cambodia" },
    { code: "+856", name: "Laos" },
    { code: "+886", name: "Taiwan" },
    { code: "+960", name: "Maldives" },
    { code: "+961", name: "Lebanon" },
    { code: "+962", name: "Jordan" },
    { code: "+963", name: "Syria" },
    { code: "+964", name: "Iraq" },
    { code: "+965", name: "Kuwait" },
    { code: "+967", name: "Yemen" },
    { code: "+968", name: "Oman" },
    { code: "+970", name: "Palestine" },
    { code: "+973", name: "Bahrain" },
    { code: "+975", name: "Bhutan" },
    { code: "+976", name: "Mongolia" },
    { code: "+979", name: "International Premium Rate Service" },
    { code: "+992", name: "Tajikistan" },
    { code: "+993", name: "Turkmenistan" },
    { code: "+994", name: "Azerbaijan" },
    { code: "+995", name: "Georgia" },
    { code: "+996", name: "Kyrgyzstan" },
    { code: "+998", name: "Uzbekistan" },
  ]
  